### ISSUE TITLE
Issue running strace on v3.4 kernel (armv7)

### ISSUE THREAD

**Issue by z3ntu** [strace/strace#163]
Hi,
first of all I'm not expecting anyone helping me with this issue as kernel 3.4 is obviously really outdated etc but I'm just asking if someone knows what's going on by any chance.

I'm trying to run strace on a kernel shipped with an Android phone (armv7) based on Linux v3.4 plus a bunch of Android and Qualcomm patches and backported stuff. I've first noticed strace not working about a year ago, I'm not sure if it worked before that (I think so?) but I can't pinpoint the issue to anything.
When running strace on most more complicated binaries (not in simple hello world programs), the binary segfaults more or less immediately. I have a few examples of this:
```
$ strace /usr/sbin/sshd
execve("/usr/sbin/sshd", ["/usr/sbin/sshd"], 0xbec97d10 /* 21 vars */) = 0
set_tls(0xb6f7d40c)                     = 0
set_tid_address(0xb6f7c7d4)             = 3042
brk(NULL)                               = 0xb7010000
brk(0xb7012000)                         = 0xb7012000
mmap2(0xb7010000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb7010000
open("/etc/ld-musl-armhf.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libcrypto.so.1.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbe84e618) = -1 ENOSYS (Function not implemented)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
(the following binary is not even using musl libc but bionic libs)
```
$ strace ./somebinary 
execve("./somebinary", ["./somebinary"], 0xbed43de0 /* 17 vars */) = 0
set_tls(0xbedfed9c)                     = 0
getpid()                                = 3078
mmap2(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6ec7000
madvise(0xb6ec7000, 12288, MADV_MERGEABLE) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
```
$ strace qmicli
execve("/usr/bin/qmicli", ["qmicli"], 0xbed2dd20 /* 21 vars */) = 0
set_tls(0xb6f6840c)                     = 0
set_tid_address(0xb6f677d4)             = 3082
brk(NULL)                               = 0xb6fc6000
brk(0xb6fc8000)                         = 0xb6fc8000
mmap2(0xb6fc6000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6fc6000
open("/etc/ld-musl-armhf.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libqmi-glib.so.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libqmi-glib.so.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libqmi-glib.so.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbeb7c618) = -1 ENOSYS (Function not implemented)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
When running strace under gdb I got the following backtrace (with musl libc debug symbols):
```
Program received signal SIGSEGV, Segmentation fault.
0xb6fb4ea8 in __syscall4 (n=175, d=8, c=0, b=-1090520184, a=2) at ./arch/arm/syscall_arch.h:75
75      ./arch/arm/syscall_arch.h: No such file or directory.
(gdb) bt
#0  0xb6fb4ea8 in __syscall4 (n=175, d=8, c=0, b=-1090520184, a=2) at ./arch/arm/syscall_arch.h:75
#1  __restore_sigs (set=set@entry=0xbefffb88) at src/signal/block.c:43
#2  0xb6fb4f48 in raise (sig=11) at src/signal/raise.c:11
#3  0x2a019960 in terminate () at strace.c:3700
#4  main (argc=<optimized out>, argv=<optimized out>) at strace.c:3726
```
I've tried everything from the normal strace from Alpine Linux, self-compiled from git master, static binary with glibc and the binary from https://github.com/andrew-d/static-binaries/blob/master/binaries/linux/arm/strace (this version is 5 years old so it also can't be an issue in a new strace version)

I guess it's something in the kernel or the kernel configuration (remember, it's a v3.4 kernel with not even all 3.4-stable patches). I've also tried this on another (previously) Android phone with kernel 3.4 and had the same issues there.

Thanks for your help and this great utility :)

**edit:** just checked, on a 3.4.113 (and 3.4.0) kernel in x86_64 qemu it works fine, so this is either arm or kernel config or extra kernel patches / missing kernel patches

**Comment by z3ntu** [comment]
Apparently Google/Qualcomm broke ptrace with commit https://android.googlesource.com/kernel/common/+/66a240a7cc7c586f1a644316c6cb0eba103a7aa9%5E%21/ and this was then fixed by commit https://android.googlesource.com/kernel/common/+/a43a2ed2a3cb0216db81c87e12d08f85f7baad3d%5E%21/#F0 - and the latter was missing in this particular kernel.
